spring:
  application:
    name: demo-keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/testapi
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      resource-id: application
      principal-attribute: preferred_username
application:
  keycloak:
    enabled: true
management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
logging:
  level:
    org:
      springframework: DEBUG
      springframework.boot.autoconfigure: ERROR